### ISSUE TITLE
Problems in reproducibility of mediation analysis script

### ISSUE THREAD

**Issue by javimangal** [wangzlab/population_airway_microbiome#1]
Hi, 

While attempting to reproduce the mediation analyses, I was not able to do so. The warning pointed to object 'TM7' not being found. I was only able to retrieve 64 results for the Biofuel   ->   Microbial feature  ->   FEV1/FVC before the code aborted. 

I am attaching a scrrenshot of the error. 

![image](https://github.com/wangzlab/population_airway_microbiome/assets/126788934/1647a28b-cdd1-4ced-bda8-396d45ba9cfa)

**Comment by wangzlab** [comment]
The problem described in your request is because the taxa TM7-3 has a special character '-' which cannot be recognized by the code. We have uploaded a new script [mediationAnalysis_v2.r](https://github.com/wangzlab/population_airway_microbiome/blob/main/Mediation%20analysis%20Figure%202/mediationAnalysis_v2.r) to the same folder that should fix this problem.
